### ISSUE TITLE
FileNotFoundError 

### ISSUE THREAD

**Issue by liguang9902** [waybyte/platform-logicrom#10]
Hello，I set up VScode and PlatformIO under Window10, when the [arduino-blink example](https://github.com/waybyte/platform-logicrom/tree/master/examples/arduino-blink) compiles,in the quectel_mc60 environment, it's great. However, in the ec200u environment ,I got the error 

> 
> *** Error 3221225775
> Traceback (most recent call last):
>   File "C:\Users\LiGuang\.platformio\packages\framework-logicromsdk\tools\rda8910\pacgen.py", line 1238, in <module>
>     sys.exit(main(sys.argv[1:]))
>   File "C:\Users\LiGuang\.platformio\packages\framework-logicromsdk\tools\rda8910\pacgen.py", line 1228, in main
>     ret = args.func(args)
>   File "C:\Users\LiGuang\.platformio\packages\framework-logicromsdk\tools\rda8910\pacgen.py", line 856, in cfg_image
>     if os.path.getsize(args.path) == 0:
>   File "C:\Users\LiGuang\.platformio\python3\lib\genericpath.py", line 50, in getsize
>     return os.stat(filename).st_size
> FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\Users\\LiGuang\\Desktop\\platform-logicrom-master\\examples\\gpio-blink\\.pio\\build\\ec200u\\firmware.img'
> *** Error 1
> 
I have no idea to solve this issue.

**Comment by ajaybhargav** [comment]
I have seen this issue where defender blocks application making changes to filesystem. So can you try to change path to a **different drive** (preferably) or directory where "Windows Defender" is not monitoring.

**Comment by liguang9902** [comment]
Thank you, I have solved this issue:)
