### ISSUE TITLE
LogicRom - Arduino platform Blink example EC200U-EU

### ISSUE THREAD

**Issue by Thieuqp** [waybyte/platform-logicrom#11]
Dear Guys!

I've tryed test EC200U-EU module, with Arduino platform, but no thing happened when upload done and restart, pls help me this issue. Thank very much!

![image](https://user-images.githubusercontent.com/13095712/224878866-fb0f2785-3fe2-40b6-a5ed-79774886f31a.png)
![image](https://user-images.githubusercontent.com/13095712/224878989-ffc3b008-2f5a-4d35-9768-4a27de07383b.png)
[](url)

**Comment by ajaybhargav** [comment]
We need to update Arduino documentation. Please make sure you've followed the steps mentioned:
https://github.com/waybyte/platform-logicrom#get-free-personal-license

If device is already added then make sure to turn in on once (with SIM) and let it activate itself.

**Comment by Thieuqp** [comment]
Dear

I've inserted the simcard, and module have get an IP OK. but i'dont know how to get license ok.

**Comment by ajaybhargav** [comment]
run getlic command on console

**Comment by Thieuqp** [comment]
Dear Guys, which port? i send "getlic" but no thing to response :(
![image](https://user-images.githubusercontent.com/13095712/224908734-5ce26ca1-cae8-464e-bc90-ba01f97c2436.png)

**Comment by ajaybhargav** [comment]
Port 0 to run all commands by default. If "devinfo" command shows UID value other than 100, then device is already active. try to flash your program again.
You can also confirm from your account under "Devices" menu -> Action column -> view logs

Also in your application program, make sure you **select STDIO port as /dev/ttyUSB0** to see console prints. By default its set to **None**
![image](https://user-images.githubusercontent.com/927133/224911652-6c86a657-540d-45d0-babc-f4d6b4c5e280.png)

**Comment by Thieuqp** [comment]
I can't view any thing in console although choise configs as you ask.

:(

**Comment by ajaybhargav** [comment]
can you share current selection in Arduino IDE with screenshot?
Also share device IMEI last 5 digits.

**Comment by Thieuqp** [comment]
Dear, the last part imei: xxxx5054592045

![image](https://user-images.githubusercontent.com/13095712/224923709-53b8950e-0b35-4cd8-ab2d-e28ded758fe5.png)
![image](https://user-images.githubusercontent.com/13095712/224923857-9d1483d6-9531-4013-8a14-71968c04cc69.png)

**Comment by ajaybhargav** [comment]
Device with xxxx5054592045 is already activated. Did you rebuild and flash your code after changing STDIO port?

**Comment by Thieuqp** [comment]
i rebuild and reflash some time, but no happended in Buildin_led (GPIO_22). 

below is things i receiver via serial port 2
![image](https://user-images.githubusercontent.com/13095712/224936805-dd120459-3ce5-4d08-a419-d49fe1f84e8b.png)

**Comment by ajaybhargav** [comment]
you opened wrong port, Use an external terminal instead. Open "Unisoc Serial Port 0", which is COM32 in your case.

**Comment by ajaybhargav** [comment]
Sorry, We just realized that Arduino core is not updated after changes to SDK. Its still using old core which is incompatible with SDK. We are working on Arduino update to include network related features as well. I suggest you try Logicrom SDK instead via PlatformIO.

We will update this thread once Arduino update is released.

**Comment by Thieuqp** [comment]
Many thanks. Pls update soon!!!!

**Comment by Thieuqp** [comment]
> Sorry, We just realized that Arduino core is not updated after changes to SDK. Its still using old core which is incompatible with SDK. We are working on Arduino update to include network related features as well. I suggest you try Logicrom SDK instead via PlatformIO.
> 
> We will update this thread once Arduino update is released.

Dear Guys!!

have any update for arduino platform?

**Comment by ajaybhargav** [comment]
Update process will take some time, We have released core update (0.2.0) right now, followed by SDK, Arduino and then platform update.

**Comment by ajaybhargav** [comment]
@Thieuqp please update your setup and verify if things are working with updated Arduino framework.

**Comment by Thieuqp** [comment]
Thank for support, it is OK!!!!

Pls share more examples for IOT. Thánks

**Comment by ajaybhargav** [comment]
What examples are you looking for?

**Comment by moustafasaad1979** [comment]
is the EC200U-EU is Support Interrupt Pins? @ajaybhargav

**Comment by ajaybhargav** [comment]
@moustafasaad1979 yes. interrupt is supported. Please open a different issue as this one is already closed.
