### ISSUE TITLE
Ai-Thinker A9G: activation problem

### ISSUE THREAD

**Issue by qrkot** [waybyte/platform-logicrom#12]
Hi,

I have Ai-Thinker's A9G board, it works well with Ai-Thinkers firmware, AT commands, GPRS, GPS, Internet, all stuff.
I registered its IMEI on your website.
Then I flashed [Logicrom core](https://github.com/waybyte/logicrom_core/tree/master/2G_RDA8955) with Coolwatcher.
It seems to work, but I can't figure out how to activate the firmware:

```
NW: GPRS Disable fail
NW: SIM card ready
NW: GSM - Registered
NW: GPRS - Registered
NETWORK: APN Not Found, Please configure!
devinfo

UUID:08b91930c86016000000000000000000
IMEI:000000000000000
UID:100
CCID:89701021099225462500
ATI

AT Commands not present on this system, Use help for available commands
getlic

+SER: -4
```

It needs an APN indeed, but I don't know how to set one up.
Actually, I can't figure out any command besides `devinfo`.
`help` command just hangs.

What should I do next to make A9G work?

**Comment by ajaybhargav** [comment]
Yes I understand, we compiled and added latest newlib support to toolchain, however toolchain is still old. c++ also works with older standard.

You can get original core from AI thinker account (https://github.com/Ai-Thinker-Open/GPRS_C_SDK/blob/master/platform/csdk/release/SW_V2130_csdk.lod)
I did not had issue with board I had with me. I understand there is no option to set APN. We can provide an updated core with APN command and maybe option to update IMEI as well.

**Comment by qrkot** [comment]
I managed to flash some old official AFW I could find (not that you point at).
It kinda works, but not quite, I'm afraid:
```
ATI

Ai_Thinker_Co._Ltd.
A9/A9G
V02.02.20190915R

OK
AT+GSN

000000000000000

OK
AT+CCID

+CCID: 89701021099225xxxx

OK
```

I'll try to flash that LOD  you mentioned and report back.

**Comment by ajaybhargav** [comment]
set IMEI with AT command : at+egmr=1,7,"imei"

**Comment by qrkot** [comment]
Hi again,

Thanks!
I flashed back Ai-Thinker's official FW to work with AT commands. It was Ok.
I managed to set my previous IMEI back up with AT+EMGR=1,7,"imeinum". It was Ok too.
I flashed Logicrom FW again, it seemed to be Ok too.

As far as I can understand, the only problem now is APN settings?

```
devinfo

UUID:08b9xxxxxxxxxxxxxxxx
IMEI:8679xxxxxxxxx
UID:100
CCID:8970xxxxxxxxxxx
NW: GPRS Disable fail
NW: SIM card ready
NW: GSM - Registered
NW: GPRS - Registered
NETWORK: APN Not Found, Please configure!
```

BTW, are there any built-in commands besides `devinfo`?
I couldn't find any list or manual on that.

**Comment by ajaybhargav** [comment]
Usually APN can be found with APN list available inside the core. It might be possible that your network APN is not supported by firmware.

Can you please test this new build:

* Added help command to show available command list
* Added APN command to configure APN

You can set APN with "apn=<value>", then turn GPRS off (network=off) and on again (network=on).
[logicrom_rda8955_core_v0.2.1.zip](https://github.com/waybyte/platform-logicrom/files/11515416/logicrom_rda8955_core_v0.2.1.zip)

**Comment by qrkot** [comment]
Thank you, I will test your build and reply back!
My current APN should be "internet".

**Comment by ajaybhargav** [comment]
I tried setting APN and it worked without problem. Here I rebuild one more time. Please try.

[logicrom_rda8955_core_v0.2.1.zip](https://github.com/waybyte/platform-logicrom/files/11515863/logicrom_rda8955_core_v0.2.1.zip)

**Comment by qrkot** [comment]
Still fails:
```
reboot

+SER: 14
NW: SIM card ready
NW: GSM - Registered
NW: GPRS - Registered
NETWORK: APN Not Found, Please configure!
apn=internet

Fail to set APN: -20
```

**Comment by ajaybhargav** [comment]
ok, Found the issue. I will send a fix.

**Comment by qrkot** [comment]
APN settings is working now.
But this time `network=off` fails, I think.
```
apn=internet

APN set to internet
network=off

network=on

NW: GPRS Disable fail
NW: SIM card ready
NW: GSM - Registered
NW: GPRS - Registered
NETWORK: APN Not Found, Please configure!
```

**Comment by qrkot** [comment]
alnash

Honestly, on your website where was no module name I could associate with A9G, so I selected one rather randomly...

**Comment by ajaybhargav** [comment]
Yes it worked. Try to build an application, let us know if there are any issues.

We classified modules into broader catagory to make it simple :)

4G: RDA8910, ASR1601, ASR1603
2G/GSM: Mt6261,mt2503,rda8955

but I guess we need to mention it more clearly. Thanks for feedback.

**Comment by qrkot** [comment]
Thanks a lot for your help!

I'll try to build some app now, I will report if there's any issues.
