### ISSUE TITLE
Flash Logicrom core firmware

### ISSUE THREAD

**Issue by Akill047** [waybyte/platform-logicrom#14]
Having toruble with flashing the core firmware in my N58 mocule.
 I have followed these steps.

1. Register account on [waybyte.in](https://waybyte.in/register)
2. Click on [Register Free Device](https://waybyte.in/devices/register) from left menu
3. Enter device details
4. Flash Logicrom core firmware 
5. Put a valid SIM card in device
6. Turn on the device, It should accquire the license
7. If device fail to do so, run "getlic" command from device console Port (USB Port 0 or Main UART) to try again.

But i couldn't able to figure out how to flash the  Logicrom core firmware,

I have registered the device and also generated the Licence key for the process. 
![image](https://github.com/waybyte/platform-logicrom/assets/93131356/dbc9a672-0dca-4857-96fc-e0f83ce32685)

please suggest me how to move forward from here. 
I want to access the Logicrom SDK.
And paralelly i also made the setup of PlatformIO in my VS code. I am trying to use Logicrom SDK to test my module with examples codes and based on that want to develop the code for MQTT  based setup.

**Comment by ajaybhargav** [comment]
hi @Akill047 

You can download latest core firmware PAC from here https://github.com/waybyte/logicrom_core/tree/master/N58-CA

Use flasher software provided by Neoway to flash the PAC file.

> I have registered the device and also generated the Licence key for the process.

This is required for production flasher that we provide to customers.

If you face any issue in flashing core, please drop us an email.

**Comment by Akill047** [comment]
Hi @ajaybhargav .
Thanks for the prompt response.  I just contacted the Neoway support team they are going to help me setup the flasher software. I just started working on this board.

**Comment by ajaybhargav** [comment]
If you do not have a flasher, please drop an email, I will help you out.
