### ISSUE TITLE
just getting started with EC200U-CNAA

### ISSUE THREAD

**Issue by Himanshu-Rokde** [waybyte/platform-logicrom#16]
Can you please guide me with flashing the EC200U-CN with logicrom firmware ?

I don't know where I can get the Logicrom flasher as well, if you can provide me

**Comment by ajaybhargav** [comment]
Please download from following link: [Logicrom Flasher Setup v25.20.39.1.exe](https://1drv.ms/u/s!ApZTubTDtl8OwJskdlhvkqxTMsAgKg?e=uoeats)

get flasher license from your Waybyte account.
