### ISSUE TITLE
Forced to install an optional package.

### ISSUE THREAD

**Issue by Nick-Miras** [waybyte/platform-logicrom#18]
I am running PlatformIO on Gentoo. When I tried to initialize a new project for an `a9g` board, it gave me an `UnknownPackageError` regarding `waybyte/toolchain-gccmipselfrda8955`. After reading the package description of gccmipselfrda8955, it should only work on Windows operating systems; however, after reading the `platform.json` file of this repository, the package should be optional. What could be the issue here?

Result of `uname -r`:
```
6.6.13-gentoo
```

Complete error message:
```
...
Resolving a9g dependencies...
Tool Manager: Installing waybyte/toolchain-gccmipselfrda8955 @ =4.4.2
UnknownPackageError: Could not find the package with 'waybyte/toolchain-gccmipselfrda8955 @ =4.4.2' requirements for your system 'linux_x86_64'
```

**Comment by Nick-Miras** [comment]
Edit:
I've read the `platform.py` file and discovered that it is indeed required if the chipset is rda8955. However, it stumps me that the toolchain is only available for windows.

**Comment by ajaybhargav** [comment]
@Nick-Miras thanks for clarification. Sorry the windows toolchain is actually modified version of vendor provided toolchain to support c++. We tried to make linux version but failed.
