### ISSUE TITLE
Whether the AIR724 module is supported？

### ISSUE THREAD

**Issue by xfdr0805** [waybyte/platform-logicrom#5]
Air724UG_Air723UG_模块硬件设计手册V2.1.pdf

[datasheet](http://old.openluat.com/Product/file/uis8910dm/Air724UG_Air723UG_%E6%A8%A1%E5%9D%97%E7%A1%AC%E4%BB%B6%E8%AE%BE%E8%AE%A1%E6%89%8B%E5%86%8CV2.1.pdf)

**Comment by ajaybhargav** [comment]
It can be supported. Maybe in future releases.
