### ISSUE TITLE
Linux and EC200U

### ISSUE THREAD

**Issue by 0x7a657573** [waybyte/platform-logicrom#9]
I want to use your platform to develop firmware for EC200U under Debian Linux.
I set up VScode + PlatformIO and installed your platform into PlatformIO and use the [blink example](https://github.com/waybyte/platform-logicrom/tree/master/examples/gpio-blink) for a test with a little change in line 19 because I connected LED into GPIO_19 :).

`#define BLINK_GPIO		GPIO_19`

the project compiles without error and warning

> No dependencies
> Building in release mode
> Checking size .pio/build/ec200u/firmware.elf
> Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
> RAM:   [          ]   1.0% (used 5408 bytes from 524288 bytes)
> Flash: [          ]   2.4% (used 25348 bytes from 1048576 bytes)

when trying to upload I got the error `ERROR: Unable to find device.`. 
I watched dmsg log and find the EC200U Bootloader port in /dev/ttyACM0

> [22114.673793] usb 2-3: USB disconnect, device number 46
> [22115.174325] usb 2-3: new full-speed USB device number 47 using xhci_hcd
> [22115.342761] usb 2-3: not running at top speed; connect to a high speed hub
> [22115.355495] usb 2-3: New USB device found, idVendor=0525, idProduct=a4a7, bcdDevice= 0.00
> [22115.355502] usb 2-3: New USB device strings: Mfr=0, Product=0, SerialNumber=0
> [22115.364440] cdc_acm 2-3:1.0: ttyACM0: USB ACM device

for this issue, I change line 188 of rda8910.py from `if "SPRD" in port.description:` to `if "SPRD" in port.description or 1==1:` with this change, I can bypass check SPRD string into a port description, after that, I can upload firmware into EC200U.

> 
> Searching for USB Port...
> 
> Found port ttyACM0
> Download FDL1
> |##################################################| 100%
> Download FDL2
> |##################################################| 100%
> Download APP 
> |##################################################| 100%
> Resetting device to normal

but nothing is happening!

**Comment by ajaybhargav** [comment]
You need to update device core for this. I have just made all core files available for flashing, use the one which applies to you.
https://github.com/waybyte/logicrom_core

You need to register your device @ https://waybyte.in/devices/register for logicrom to work.

Let me know if you still face any issue.

**Comment by 0x7a657573** [comment]
Thank you for your replay
my module part number is `EC200U-EU` and I tried uploading the core file(.pac) with QFlash 5, core uploaded without a problem.
after that, I tried uploading the blink program, program uploaded without problems like in the past but not work again.

**Comment by ajaybhargav** [comment]
Please follow steps mentioned here:
https://github.com/waybyte/platform-logicrom#get-free-personal-license

On USB you have 3 ports:
Port 0: Application console
Port 1: AT command
Port 2: AP debug

Later check on console (uart/usb) with at command if firmware is flashed successfully.
"ATI"
check if network is fine:
"AT+CEREG?"
"AT+CSQ"

**Comment by 0x7a657573** [comment]
Thank you
I register on your website and register my EC200U IMEI and got UID for that.
in my hardware with the command `getlic` and UID finally, I think activate the device!
in sysinfo from terminal of device I got:

> Library Version: 7.2.0 f805795 - Build Nov 19 2022 20:10:10
> Core firmware: Logicrom_v0.1.0-gbba2fe73
> SDK Version: LOGICROM_SDK_V0.9.7

**Comment by ajaybhargav** [comment]
If you can access console then probably everything is working fine.
You can update your SDK and platform both.
current release is 0.9.8
